CREATE DATABASE IF NOT EXISTS workshop;
USE workshop;

CREATE TABLE IF NOT EXISTS demo_names (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
